POST http://localhost:8080/clock
Content-Type: application/json

{
"url":"	https://webhook.site/5a39dd0d-5ca5-456e-953b-2256a7212a6d"
}

###
DELETE http://localhost:8080/clock
Content-Type: application/json

{
  "url":"https://webhook.site/6de138d2-6c61-42bb-8c7e-ab2e2fbdf43a"
}

###
PUT http://localhost:8080/clock
Content-Type: application/json

{
"seconds": "6"
}